### ISSUE TITLE
Switch to per-user keys for our FileZilla Pro installation

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/archivematica-infrastructure#124]
Currently everyone in Collections Information is using the same set of IAM keys for FileZilla Pro, to connect to Archivematica and the storage service. This is suboptimal from a security perspective; it makes it harder to audit activity and revoke keys when somebody leaves.

We should move everybody to individual keys.

**Comment by agnesgaroux** [comment]
Ashley compiling a list of users holding the "communal" key
