### ISSUE TITLE
Increase stability of archivematica tasks

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/archivematica-infrastructure#143]
It looks like the clamav task is failing frequently, this is consuming the time of @aray-wellcome as it requires manual restarts. Can we improve the situation?

**Comment by kenoir** [comment]
The clamav task failrues still persist event after an upgrade. Perhaps there are some configuration options to experiment with? 

https://wellcome.slack.com/archives/CN56BRQ5B/p1704976541897729

**Comment by agnesgaroux** [comment]
See also https://github.com/wellcomecollection/archivematica-infrastructure/issues/139

**Comment by kenoir** [comment]
Closing as to be looked at in a wider piece of work.
